# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: inkscape_merge 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "inkscape_merge"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Laas Toom"]
  s.date = "2016-10-27"
  s.description = "Script to merge SVG files with CSV data-files using Inkscape, to produce\n  one outputfile (e.g. PDF) per data-row."
  s.email = "laas.toom@gmail.com"
  s.executables = ["inkscape_merge"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/inkscape_merge",
    "inkscape_merge.gemspec",
    "lib/inkscape_merge.rb",
    "lib/inkscape_merge/data_parsers.rb",
    "lib/inkscape_merge/processor.rb",
    "spec/data_parsers_spec.rb",
    "spec/fixtures/data.csv",
    "spec/fixtures/fake_inkscape",
    "spec/fixtures/test.svg",
    "spec/helper.rb",
    "spec/processor_spec.rb"
  ]
  s.homepage = "http://github.com/borgand/inkscape_merge"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Merge SVG files with CSV file using Inkscape"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<juwelier>, ["~> 2.1"])
      s.add_development_dependency(%q<rspec>, ["~> 3.5"])
    else
      s.add_dependency(%q<juwelier>, ["~> 2.1"])
      s.add_dependency(%q<rspec>, ["~> 3.5"])
    end
  else
    s.add_dependency(%q<juwelier>, ["~> 2.1"])
    s.add_dependency(%q<rspec>, ["~> 3.5"])
  end
end

